CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "password" varchar not null, "department" varchar, "position" varchar check ("position" in ('hod', 'manager', 'staff', 'system_manager')) not null default 'staff', "manager_id" varchar, "hod_id" varchar, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "expenses" ("id" integer primary key autoincrement not null, "staff_id" integer not null, "amount" numeric not null, "description" text not null, "category" varchar not null, "supporting_document" varchar not null default 'uploads/unavailable.jpg', "status" varchar check ("status" in ('pending', 'accepted', 'approved', 'rejected_hod', 'rejected_manager', 'drafted')) not null default 'pending', "created_at" datetime, "updated_at" datetime, foreign key("staff_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "departments" ("id" integer primary key autoincrement not null, "department" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "departments_department_unique" on "departments" ("department");
